/* gdal_def.h.  Generated by cmake4gdal  */

/* Define if gdal used libz*/
#define GDAL_USE_ZLIB

/* Define if gdal used internal libz*/
/* #undef GDAL_USE_ZLIB_INTERNAL */

/* Define if gdal used libcurl */
#define GDAL_USE_CURL

/* Define if gdal used odbc */
/* #undef GDAL_USE_ODBC */

/* Define if gdal used odbc-cpp */
/* #undef GDAL_USE_ODBCCPP */

/* Define if pam enable in gdal */
#define ENABLE_PAM

/* Define if gdal use geos*/
/* #undef GDAL_USE_GEOS */

/* Define if gdal use opencl*/
#define GDAL_USE_OPENCL

/* Define if gdal use armadillo*/
/* #undef GDAL_USE_ARMADILLO */

/* Define if gdal use iconv*/
#define GDAL_USE_ICONV

/* Define if gdal use internal libtiff*/
/* #undef GDAL_USE_LIBTIFF_INTERNAL */
#define GDAL_USE_TIFF

/* Define if gdal use internal libjpeg*/
/* #undef GDAL_USE_LIBJPEG_INTERNAL */
#define GDAL_USE_JPEG

/* Define if gdal use internal libpng*/
/* #undef GDAL_USE_LIBPNG_INTERNAL */
/* #undef GDAL_USE_PNG */

/* Define if gdal use internal libgif*/
/* #undef GDAL_USE_LIBGIF_INTERNAL */
/* #undef GDAL_USE_GIF */

#define GDAL_USE_EXPAT
/* #undef GDAL_USE_POSTGRESQL */
#define GDAL_USE_SQLITE3
/* #undef GDAL_USE_MYSQL */
/* #undef GDAL_USE_LIBKML */

/* #undef GDAL_USE_LIBJSONC_INTERNAL */

/*** RASTER FORMATS ***/
#define GDAL_ENABLE_DRIVER_GTIFF
/* #undef GDAL_ENABLE_DRIVER_JPEG */
#define GDAL_ENABLE_DRIVER_HFA
/* #undef GDAL_ENABLE_DRIVER_BMP */
/* #undef GDAL_ENABLE_DRIVER_DIMAP */
#define GDAL_ENABLE_DRIVER_MEM
/* #undef GDAL_ENABLE_DRIVER_RAW */
#define GDAL_ENABLE_DRIVER_VRT
/* #undef GDAL_ENABLE_DRIVER_PNG */
/* #undef GDAL_ENABLE_DRIVER_GIF */
/* #undef GDAL_ENABLE_DRIVER_TIL */

/*** VECTOR FORMATS ***/
/* #undef OGR_ENABLE_DRIVER_MITAB */
/* #undef OGR_ENABLE_DRIVER_CSV */
/* #undef OGR_ENABLE_DRIVER_DXF */
#define OGR_ENABLE_DRIVER_GEOJSON
#define OGR_ENABLE_DRIVER_MEM
#define OGR_ENABLE_DRIVER_VRT
/* #undef OGR_ENABLE_DRIVER_GPX */
#define OGR_ENABLE_DRIVER_SHAPE
/* #undef OGR_ENABLE_DRIVER_WFS */
/* #undef OGR_ENABLE_DRIVER_PG */
/* #undef OGR_ENABLE_DRIVER_SQLITE */
/* #undef OGR_ENABLE_DRIVER_MYSQL */
/* #undef OGR_ENABLE_DRIVER_LIBKML */
/* #undef OGR_ENABLE_DRIVER_GML */
#define OGR_ENABLE_DRIVER_KML
